name: Deploy Resources

permissions:
 id-token: write
 contents: read

on:
 push:
   branches:
     - main

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Deploy using reusable pipeline
       uses: SamuelMolling/workflows/.github/workflows/cdk-deploy.yaml@main