name: Deploy Resources

permissions:
 id-token: write
 contents: read

on:
 push:
   branches:
     - main

jobs:

  test: 
    environment: dev
    runs-on: ubuntu-latest
  deploy:
    uses: SamuelMolling/workflows/.github/workflows/cdk-deploy.yaml@main
    secrets:
      AWS_GITHUB_ACTIONS_ROLE: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
      AWS_TARGET_REGION: ${{ secrets.AWS_TARGET_REGION }}
